on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [9.0.x, 8.0.x]
    
      
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Run tests
      if: success()
      run: dotnet test

    - name: Show PR details
      if: github.event_name == 'pull_request'
      run: |
        echo "PR number: ${{ github.event.pull_request.number }}"
        echo "Author: ${{ github.event.pull_request.user.login }}"
        echo "Base branch: ${{ github.event.pull_request.base.ref }}"

    - name: Show commit details
      if: github.event_name == 'push'
      run: |
        echo "Commit message: ${{ github.event.head_commit.message }}"
        echo "Commit author: ${{ github.actor }}"
        
    - name: Show manual trigger details
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Triggered by: ${{ github.actor }}"
        echo "Inputs: ${{ toJSON(github.event.inputs) }}"
          


    - name: Visa GitHub- och runner-context
      shell: bash
      run: |
        echo "GitHub context:"
        echo "${{ toJSON(github) }}"
        echo "Runner context:"
        echo "${{ toJSON(runner) }}"
